add pagination to list_measurments()
vikinganalytics/mvg pull request #191
Opened 2022-12-23 14:47 UTC by tuix

# Description

Include a summary of this pull request

New dependencies: (Added to requirements_*.txt)

Fixes # (potential issues that are fixed by this PR)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue -> bump patch)
- [ ] New feature (non-breaking change which adds functionality -> bump minor version)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected -> bump major version)
- [ ] Documentation Update
- [ ] CI/CD workflows Update

## Checklist

- [ ] I have added tests that prove that my fix/feature works
- [ ] Linters pass locally and I have followed PEP8 code style
- [ ] New and existing tests pass locally
- [ ] I have updated the documentation if needed
- [ ] I have commented hard-to-understand areas in the code

## Requirements

- [ ] I have updated the MVG version

2023-01-04 10:16 UTC, claezon requested changes
A proposal for an overall change regarding this PR to enable pagination.

2023-01-04 10:16 UTC, claezon commented on mvg/mvg.py
> +        list_all=True,
We should also incorporate the pagination in this method to enable it for the clients (/Pipeline). Also, I suggest that we always default to a limit.

2023-01-04 10:16 UTC, claezon commented on mvg/mvg.py
> +        num_meaurements = resp_first["total"]
Typo (num_measurements).

2023-01-04 10:29 UTC, tuix commented on mvg/mvg.py
> +    def list_measurements(self, sid: str, list_all=True) -> list:
I am not sure whether pipeline would require the pagination at this time. This was done this way to keep it backwards compatible where this method would return all results. If we want to incorporate pagination here that would require update in jupyter notebooks that use this and I wanted this to be merged ASAP. If you don't mind we can do it this way for now and I can create a separate issue for introducing pagination later.

2023-01-04 10:43 UTC, claezon commented on mvg/mvg.py
> +    def list_measurements(self, sid: str, list_all=True) -> list:
Yes, I suspected that was the reason. But we could still let the client use the pagination parameters, but the response would still be an array (leaving out the pagination meta: offset, limit, total...)? Later, in connection with implementing versioning of the API(s), we could replace the response array with a uniformed response object.

2023-01-04 12:49 UTC, tuix commented on mvg/mvg.py
> +    def list_measurements(self, sid: str, list_all=True) -> list:
I added offset and limit to both "list_*" methods. by default it returns all measuremnts

2023-01-04 14:36 UTC, claezon requested changes
Nice Mohsen! A few small suggestions that you can choose to ignore and a typo.

2023-01-04 14:36 UTC, claezon commented on mvg/mvg.py
> +                params["offset"] = offset
A suggestion to reduce the level of nested if statements is to move the declaration of params to the beginning:

```python
    params = {}
    if limit is not None:
        params["limit"] = limit
    if offset is not None:
        params["offset"] = offset

    if not params:
        # List all by default
    else:
        # Use pagination
```

2023-01-04 14:36 UTC, claezon commented on mvg/mvg.py
> +        ):
I believe checking the `query_params` would be enough.

2023-01-04 14:36 UTC, claezon commented on mvg/mvg.py
> +        query_params = {}
The name `params` is used in `list_measurements()`. Use the same name?

2023-01-04 14:36 UTC, claezon commented on mvg/mvg.py
> +        num_meaurements = resp_first["total"]
Typo (num_measurements).

2023-01-05 15:08 UTC, claezon approved these changes
Nice work Mohsen!

2023-01-05 15:55 UTC, merged